### ISSUE TITLE
Interactive Issue

### ISSUE THREAD

**Issue by MayhemJim** [SaviorXTanren/mixer-mixitup#105]
The screen I get when in the interactive menu is different than what should be as on the help page.  Screenshots inserted.

![miu1](https://user-images.githubusercontent.com/36520386/36281418-975a1960-126b-11e8-9ae4-fd7eaa474024.PNG)
![miu2](https://user-images.githubusercontent.com/36520386/36281423-99c5370c-126b-11e8-91bb-5a05d34005a6.PNG)

**Comment by SaviorXTanren** [comment]
The only thing that is different is the Mixer Labs quick access button in the upper-left corner. You haven't added any Interactive Commands for those buttons you have, which is why you're not seeing the same buttons on the Wiki. Click on the "Add Command" button, create the interactive command for that button, then you'll see the buttons you're seeing on the Wiki.

**Comment by MayhemJim** [comment]
Those 2 commands were set up in Mixer labs and then Firebot.  Is there not a way to import the settings from Firebot?  I ask because I didn't see an option for a video, only chat and sound commands.

**Comment by SaviorXTanren** [comment]
We don't currently support importing from Firebot, only ScorpBot & Soundwave.

You want to select the 3rd option when creating a command, "Advanced Command". The Basic Chat & Sound options are there just to simplify the process since commands that only do Chat or Sound are some of the most common things a user does.

We don't have a "direct" video option with our Overlay right now, but there about 3 other ways you can do it currently depending on your technical expertise. Easiest way would be to make a source in OBS or XSplit, add the video you want to it, then use our OBS/XSplit connectivity to show or hide the video.

**Comment by MayhemJim** [comment]
Ok thanks.  I'm just a little confused about the triggers for the advanced.  Mouse & key up & down.  Thanks for answering my questions, it is a clean looking app you've built.  Apologies for being such a noob.

**Comment by SaviorXTanren** [comment]
You're good :)

The triggers are basically "when" we should run you command. Mixer allows users to either click the button or you can associate a keyboard key with it. The Down corresponds to the button being pressed, while the up corresponds to the button being released.

Most people don't care about this option, so we plan on just pre-setting it for you in the future.
