### ISSUE TITLE
Bot and host

### ISSUE THREAD

**Issue by NIGHTFALLW0LF94** [SaviorXTanren/mixer-mixitup#127]
the bot isn't showing up in my mix it up also the host coins aren't going into into my currency

**Comment by SaviorXTanren** [comment]
Hey @NIGHTFALLW0LF94 , I'm going to need a little bit more information to help you.

1) What do you mean by "the bot isn't showing up"? Did you log in a Bot account in the Services area? Are they not showing up in the Chat User list in Mix It Up and/or Mixer? Did the bot actually send a message to chat at all before you tried looking for it? Just connecting the bot doesn't always make it appear in the chat list, a user has to actually say something typically or they'll not show up in the list.

2) I'm assuming you've set a number for "On Host Bonus" for your currency/rank? Are you not seeing that for a specific person or everyone?

**Comment by NIGHTFALLW0LF94** [comment]
1. If I even want the bot option to pop out I have to close it and reopen it about 50 times.

2. Yes, host makes them have another currency doesn't give him the currency into the currency point system I have set up

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SaviorXTanren** [comment]
1) By pop-out, are you talking about the expandinf sections in the Services area? You just need to click in the center of the long box to make it pop out, you shouldn't need to restart the app. I feel like there's a disconnect between what you're telling me and what's happening because I'm not seeing what issue you're running in to. At this point, I'm going to need to see what exactly you're having an issue with, either some screenshots or a Discord call.

2) Can you send me a picture of your Currency Editor window so I can see what settings you have?
