### ISSUE TITLE
Tooltip Support for Interactive Board

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#143]
Mixer now supports tooltips for buttons / actions on the interactive board. It would be awesome if Mix it Up supported the option to customize the tooltip for the button(s). Not a bug, just a feature request. Credit to you guys for making a fantastic bot, you guys have the best bot on mixer, period. Nailed it you guys!

**Comment by SaviorXTanren** [comment]
Hey @UnderSwitch thanks for the suggestion. Since there is already an easy interface to edit the tooltips for a button on Mixer's Developer Labs, I would tend to lean against doing it to avoid "reinventing the wheel" to build the UI to re-do what Mixer already has. We've specifically tried to limit our UI just to thinks that have a little more direct interaction/effect with Mix It Up (EX: Sparks & Cooldown).

Now, that said, what was your scenario you were hoping for? Was it just the ability to edit the tooltips for your buttons (Which you can do in the Dev Lab currently) or were you looking for some sort of dynamic updating of the tooltip (EX: When the button's pressed, the tooltip is updated to say something different)?

**Comment by UnderSwitch** [comment]
Makes sense for sure! I was honestly just thinking a simple tooltip text editing option, but the option to dynamically change it with other commands (IE: buttons mostly) would be very interesting. Not sure if people would find the feature too useful so I'm not sure if it's worth the time but it's cool none the less. For some little things that would be awesome to see outside of the button tooltip support:

1) On the commands page, it would be awesome to be able to see the cooldown time without editing the command. So in the item table item. Just a little thing similar to the interactive page.
2) On the events page, it would be awesome to have a user joined option. This event would be fired every time a user joins the stream. I'm thinking this event will add some cool interactions every time someone joins the stream.

That's about all I got, like I said I've tried other bots for Mixer and you guys have the best bot by far. Love the UI/UX and simplicity, keep up the great work guys!

**Comment by SaviorXTanren** [comment]
So, I'll probably not be adding tooltip editing within the app, for mainly the reason I stated. Anything we do that takes a dependency on Mixer's APIs we have to maintain and keep up with it, so trying to minimize that as much as possible gives me more time to work on other features. It's the same reason why we shelved a full UI for building Interactive controls; the amount of time and maintenance it would require would take away from other work and there's already a fairly easy way to do it all currently.

As for your other two suggestions:

1) I should be able to fit that in on the page, though it'll most likely be limited to just the number time, I won't include whether it's a global or individual cooldown, as that will just take up too much space.

2) We have a backlog item already for adding this and other Chat related events (Leave, Ban, Timeout, Purge), along with user-specific events (EX: When a specific user joins chat)

Thanks for the suggestions!
