### ISSUE TITLE
Web Pages Don't Seem to Work

### ISSUE THREAD

**Issue by UnderSwitch** [SaviorXTanren/mixer-mixitup#166]

**Comment by UnderSwitch** [comment]
So, I'm using a local .html file that I coded. Not using any scripts in this file. Only inline css & html. It doesn't seem to load at all.

**Comment by SaviorXTanren** [comment]
Local HTML pages won't work in the Overlay due to technical reasons with cross-side scripting. If you want use a local web page, you'll need to use one of the following:

- Streaming Software Web Browser Source Action: https://github.com/SaviorXTanren/mixer-mixitup/wiki/Actions#web-browser-source

- Overlay HTML Action: https://github.com/SaviorXTanren/mixer-mixitup/wiki/Actions#web-browser-source
