### ISSUE TITLE
Feature Request Amazon Music

### ISSUE THREAD

**Issue by InhumAnts** [SaviorXTanren/mixer-mixitup#286]
I do not know if it is possible but if you could get Amazon Music/ Music Unlimited to work for song requests that would be awesome & If the x-ray lyrics were able to function on the overlay that would be next level. just a shower thought

**Comment by TyrenDe** [comment]
Sadly, I don't think there is any Developer APIs for Amazon Music.   https://forums.developer.amazon.com/questions/58421/amazon-music-api.html

I'm not sure if this has changed since this was posted in 2017, but I'm guessing not. If you find something contrary to this, let us know, but without official APIs, we can't integrate it.
