### ISSUE TITLE
MixItUp - "Unable to initialize the SongRequest service"

### ISSUE THREAD

**Issue by xispeiro** [SaviorXTanren/mixer-mixitup#304]
Whenever I try to start the songrequest, MixItUp presents me with this message and at the end says "try again".
I do not know how to solve this problem. MixItUp has a new update every day but this problem is never solved. He says that for SongRequest to work it is necessary to have an action. I already created the action but even then I can not activate this option.
In my opinion, the mixitup should be integrated into the lightstream within the signature to the mixer pro.
Does anyone have any ideas on how to solve the SongRequest problem?

**Comment by SaviorXTanren** [comment]
The github is not for reporting support questions, please use the Discord for this: https://discord.gg/6Y7P3D

It sounds like you don't have YouTube or Spotify fully enabled, but it also sounds like you're streaming from your Xbox due to you mentioning LightStream. If you're streaming from your Xbox, you won't be able to use Song Requests, as you need to be streaming from a PC in order to capture the audio for the music.
